content/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, url
from content.views import PageDetailView, PagesListView


urlpatterns = patterns('content.views',
    url(r'^$', PagesListView.as_view(), name='pagelist'),
    url(r'^(?P<slug>\w+)_(?P<pk>\d+)/$', PageDetailView.as_view(), name='page'),
)

kernel/urls.py
#-*- coding:utf-8 -*-
"""cms_cpa URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from catalog.views import MainView, CategoryListView, ItemDetailView, ItemGoRedirectView
from content.views import Robotstxt

urlpatterns = [
    url(r'^cat_(?P<slug>\w+)_(?P<pk>\d+)/$', CategoryListView.as_view(), name='category'),
    url(r'^item_(?P<slug>\w+)_(?P<pk>\d+)/$', ItemDetailView.as_view(), name='item'),
    url(r'^item_go/(?P<pk>\d+)/$', ItemGoRedirectView.as_view(), name='redirect_item'),
    url(r'^robots.txt$', Robotstxt.as_view(), name='robotstxt'),

    url(r'^page/', include('content.urls', namespace='content')),
    url(r'^$', MainView.as_view(), name='home'),

    url(r'^admin/', include(admin.site.urls)),
]

# Инициализируем папку media
if settings.DEBUG:
    if settings.MEDIA_ROOT:
        from django.conf.urls.static import static
        from django.contrib.staticfiles.urls import staticfiles_urlpatterns
        urlpatterns += static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)
    # Эта строка опциональна и будет добавлять url'ы только при DEBUG = True
    urlpatterns += staticfiles_urlpatterns()

templates/base.html
{% load staticfiles thumbnail catalog_tag cache %}<!DOCTYPE html>
<!--[if lt IE 8]>      <html class="no-js lt-ie10 lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie10 lt-ie9"> <![endif]-->
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% if seo.title %}{{ seo.title }}{% else %}{{ site.title }}{% endif %}</title>
    <meta name="keywords" content="{% if seo.keywords %}{{ seo.keywords }}{% else %}{{ site.keywords }}{% endif %}" />
    <meta name="description" content="{% if seo.description %}{{ seo.description }}{% else %}{{ site.description }}{% endif %}" />

    {% autoescape off %}{{ site.sites.meta }}{% endautoescape %}

    <!--  Google Fonts  -->
    <link href='http://fonts.googleapis.com/css?family=Pacifico|Open+Sans:400,700,400italic,700italic&amp;subset=latin,latin-ext,greek' rel='stylesheet' type='text/css'>

    <!-- Twitter Bootstrap -->
    <link href="{% static 'stylesheets/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'stylesheets/responsive.css' %}" rel="stylesheet">
    <!-- Slider Revolution -->
    <link rel="stylesheet" href="{% static 'js/rs-plugin/css/settings.css' %}" type="text/css"/>
    <!-- jQuery UI -->
    <link rel="stylesheet" href="{% static 'js/jquery-ui-1.10.3/css/smoothness/jquery-ui-1.10.3.custom.min.css' %}" type="text/css"/>
    <!-- PrettyPhoto -->
    <link rel="stylesheet" href="{% static 'js/prettyphoto/css/prettyPhoto.css' %}" type="text/css"/>
    <!-- main styles -->

    <link href="{% static 'stylesheets/main.css' %}" rel="stylesheet">



    <!-- Modernizr -->
    <script src="{% static 'js/modernizr.custom.56918.js' %}"></script>

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'images/apple-touch/144.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'images/apple-touch/114.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'images/apple-touch/72.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'images/apple-touch/57.png' %}">
    <link rel="shortcut icon" href="{% static 'images/apple-touch/57.png' %}">

    {% block metatsg %}{% endblock %}
    {% block css %}{% endblock %}
  </head>


  <body class="">

    <div class="master-wrapper">

    <!--  ==========  -->
    <!--  = Header =  -->
    <!--  ==========  -->
    <header id="header">
        <div class="container">
            <div class="row">

                <!--  ==========  -->
                <!--  = Logo =  -->
                <!--  ==========  -->
                <div class="span7">
                    <a class="brand" href="{% url 'home' %}">
                        <img src="{% static 'images/oblakomody_logo.png' %}" alt="{{ site.name }}" width="48" height="48" />
                        <span class="pacifico">{{ site.name }}</span>
                        <span class="tagline">{{ site.description }}</span>
                    </a>
                </div>

                <!--  ==========  -->
                <!--  = Social Icons =  -->
                <!--  ==========  -->
                <div class="span5">
                    <div class="top-right">
                        <strong style="font-size: 40px; color: #FC6540; font-weight: normal; position: relative;">{{ base_item|ru_price }} <b style="color: #727272; font-size: 20px; font-weight: normal; position: relative; top: -5px;">Товаров</b></strong><br>
                        <img src="{% static 'images/bg_365.png' %}" alt="365 дней возврата" title="365 дней возврата" id="img_1" />
                        <img src="{% static 'images/bg_dostavka.png' %}" alt="Бесплатная доставка" title="Бесплатная доставка" id="img_2" /><br><br>
                    </div>
                </div> <!-- /social icons -->
            </div>
        </div>
    </header>

    <!--  ==========  -->
    <!--  = Main Menu / navbar =  -->
    <!--  ==========  -->
    <div class="navbar navbar-static-top" id="stickyNavbar">
      <div class="navbar-inner">
        <div class="container">
          <div class="row">
            <div class="span9">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>

                <!--  ==========  -->
                <!--  = Menu =  -->
                <!--  ==========  -->

                <div class="nav-collapse collapse">
                  <ul class="nav" id="mainNavigation">
                      {% cache 3600 catalog_top_menu %}
                      {% catalog_top_menu %}
                      {% endcache %}
                  </ul>
                </div><!-- /.nav-collapse -->
            </div>

            <!--  ==========  -->
            <!--  = Search form =  -->
            <!--  ==========  -->
            <div class="span3">
                <form class="navbar-form pull-right" action="#" method="get">
                    <button type="submit"><span class="icon-search"></span></button>
                    <input type="text" class="span1" name="search" id="navSearchInput">
                </form>
            </div> <!-- /cart -->
          </div>
        </div>
      </div>
    </div> <!-- /main menu -->




    {% block content %}{% endblock %}


    <!--  ==========  -->
    <!--  = Footer =  -->
    <!--  ==========  -->
    <footer>
        {% block upper_footer %}{% endblock %}
        <!--  ==========  -->
        <!--  = Middle footer =  -->
        <!--  ==========  -->
        <div class="foot-dark">
            <div class="container">
                <div class="row">

                    {% for menu in footer_menu %}
                    <div class="span3">
                        <div class="main-titles lined">
                            <h3 class="title"><span class="light">{{ menu.name }}</span></h3>
                        </div>
                        <ul class="nav bold">
                         {% for sub_m in menu.footer_menu.all %}
                            <li><a href="{{ sub_m.url }}">{{ sub_m.name }}</a></li>
                         {% endfor %}
                        </ul>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div> <!-- /middle footer -->

        <!--  ==========  -->
        <!--  = Bottom Footer =  -->
        <!--  ==========  -->
        <div class="foot-last">
            <a href="#" id="toTheTop">
                <span class="icon-chevron-up"></span>
            </a>
            <div class="container">

            </div>
        </div> <!-- /bottom footer -->
    </footer> <!-- /footer -->


    </div> <!-- end of master-wrapper -->

    {% autoescape off %}{{ site.sites.footer }}{% endautoescape %}



    <!--  ==========  -->
    <!--  = JavaScript =  -->
    <!--  ==========  -->

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=126780447403102";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

     <!--  = jQuery - CDN with local fallback =  -->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript">
    if (typeof jQuery == 'undefined') {
        document.write('<script src="/static/js/jquery.min.js"><\/script>');
    }
    </script>

    <!--  = _ =  -->
    <script src="{% static 'js/underscore/underscore-min.js' %}" type="text/javascript"></script>

    <!--  = Bootstrap =  -->
    <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>

    <!--  = Slider Revolution =  -->
    <script src="{% static 'js/rs-plugin/pluginsources/jquery.themepunch.plugins.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/rs-plugin/js/jquery.themepunch.revolution.min.js' %}" type="text/javascript"></script>

    <!--  = CarouFredSel =  -->
    <script src="{% static 'js/jquery.carouFredSel-6.2.1-packed.js' %}" type="text/javascript"></script>

    <!--  = jQuery UI =  -->
    <script src="{% static 'js/jquery-ui-1.10.3/js/jquery-ui-1.10.3.custom.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-ui-1.10.3/touch-fix.min.js' %}" type="text/javascript"></script>

    <!--  = Isotope =  -->
    <script src="{% static 'js/isotope/jquery.isotope.min.js' %}" type="text/javascript"></script>

    <!--  = Tour =  -->
    <script src="{% static 'js/bootstrap-tour/build/js/bootstrap-tour.min.js' %}" type="text/javascript"></script>

    <!--  = PrettyPhoto =  -->
    <script src="{% static 'js/prettyphoto/js/jquery.prettyPhoto.js' %}" type="text/javascript"></script>

    <!--  = Google Maps API =  -->
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript" src="{% static 'js/goMap/js/jquery.gomap-1.3.2.min.js' %}"></script>

    <!--  = Custom JS =  -->
    <script src="{% static 'js/custom.js' %}" type="text/javascript"></script>

    {% block javascript %}{% endblock %}

  </body>
</html>

templates/email_code.html
<!-- Begin MailChimp Signup Form -->
<div id="mc_embed_signup">
    <form action="http://oblakomody.us7.list-manage1.com/subscribe/post?u=df8d8a367b3bac53c4567fca6&amp;id=e85ef764d9" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>                            <div class="mc-field-group">
        <input type="email" value="" placeholder="Введите ваш e-mail" name="EMAIL" class="required email" id="mce-EMAIL">
        <div class="mc-field-group">
        <label for="mce-FNAME">Введите Ваше имя </label>
        <input type="text" value="" name="FNAME" class="" id="mce-FNAME">
        </div>
            <input type="submit" value="Отправить" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary">
        </div>
        <div id="mce-responses" class="clear">
            <div class="response" id="mce-error-response" style="display:none"></div>
            <div class="response" id="mce-success-response" style="display:none"></div>
        </div>

    </form>
</div>
<!--End mc_embed_signup-->

templates/home.html
{% extends 'base.html' %}
{% load staticfiles thumbnail catalog_tag cache %}

{% block content %}
    <div class="fullwidthbanner-container">
         <br><br>
    </div> <!-- /slider revolution -->

    <!--  ==========  -->
    <!--  = Main container =  -->
    <!--  ==========  -->


    <!--  ==========  -->
    <!--  = New Products =  -->
    <!--  ==========  -->
    <div class="boxed-area blocks-spacer">
        <div class="container">

            <!--  ==========  -->
            <!--  = Title =  -->
            <!--  ==========  -->
            <div class="row">
                <div class="span12">
                    <div class="main-titles lined">
                    	<h2 class="title"><span class="light">Категории</span> товаров</h2>
                    </div>
                </div>
            </div> <!-- /title -->

            <div class="row popup-products blocks-spacer">
            {% cache 3600 category_home %}
                {% for cat in category %}
            	<div class="span3">
            	    <div class="product">
            	        <div class="product-img">
                            <div class="picture">
                                {% if not cat.images %}
                                    <img src="{% static 'images/no_img.png' %}" alt="" />
                                {% else %}
                                    {% thumbnail cat.images "400x400" crop="50% 0%" as im %}<img src="{{ im.url }}" alt="" />{% endthumbnail %}
                                {% endif %}
                                <div class="img-overlay">
                                    <a href="{{ cat.get_absolute_url }}" class="btn more btn-primary">Подробнее</a>
                                </div>
                            </div>
                        </div>
                        <div class="main-titles no-margin">
                            <a href="{{ cat.get_absolute_url }}"><h4 class="title" style="text-align: center;">{{ cat.name }}</h4></a>
                        </div>
            	    </div>
            	</div>
                {% endfor %}
            {% endcache %}
            </div>
        </div>
    </div> <!-- /new products -->

    <!--  ==========  -->
    <!--  = Most Popular products =  -->
    <!--  ==========  -->
    <div class="most-popular blocks-spacer">
    	<div class="container">

    	    <!--  ==========  -->
			<!--  = Title =  -->
			<!--  ==========  -->
    	    <div class="row">
    	    	<div class="span12">
    	    	    <div class="main-titles lined">
    	                <h2 class="title"><span class="light">Популярные</span> Товары</h2>
    	            </div>
    	    	</div>
    	    </div> <!-- /title -->

	    	<div class="row popup-products">

{#            {% cache 86400 top_items_home %}#}
{#                {% for item in items %}#}
{#		        <!--  ==========  -->#}
{#				<!--  = Product =  -->#}
{#				<!--  ==========  -->#}
{#                <div class="span3">#}
{#                    <div class="product">#}
{#                        {% if item.oldprice %}<div class="stamp red">-{{ item.percent }}%</div>{% endif %}#}
{#                        <div class="product-img">#}
{#                            <div class="picture">#}
{#                                <img src="{{ item.image }}" alt="{{ item.name }}" />#}
{#                                <div class="img-overlay">#}
{#                                    <a href="{{ item.get_absolute_url }}" class="btn more btn-primary">Подробнее</a>#}
{#                                    <a href="{{ item.get_goto_url }}" class="btn buy btn-danger">Купить</a>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                        <div class="main-titles no-margin">#}
{#                            <h4 class="title">#}
{#                                {% if item.oldprice %}#}
{#                                    <span class="striked">{{ item.oldprice|ru_price }} <small>{{ item.currency }}</small></span>#}
{#                                    <span class="red-clr">{{ item.price|ru_price }} <small>{{ item.currency }}</small></span>#}
{#                                {% else %}#}
{#                                    {{ item.price|ru_price }} <small>{{ item.currency }}</small>#}
{#                                {% endif %}#}
{#                            </h4>#}
{#                            <a href="{{ item.get_absolute_url }}"><h5 class="no-margin fixheight">{{ item.name }}</h5></a>#}
{#                        </div>#}
{#                    </div>#}
{#                </div> <!-- /product -->#}
{#                {% endfor %}#}
{#            {% endcache %}#}


            </div>
    	</div>
    </div> <!-- /most popular -->


    <!--  ==========  -->
    <!--  = Lastest News =  -->
    <!--  ==========  -->
    <div class="darker-stripe blocks-spacer more-space latest-news with-shadows">
        <div class="container">

    	    <!--  ==========  -->
			<!--  = Title =  -->
			<!--  ==========  -->
    		<div class="row">
    			<div class="span12">
    			    <div class="main-titles center-align">
    			        <h2 class="title">
    			            <span class="clickable icon-chevron-left" id="tweetsLeft"></span> &nbsp;&nbsp;&nbsp;
    			             <a href="{% url 'content:pagelist' %}">Статьи, советы, обзоры</a> &nbsp;&nbsp;&nbsp;
    			            <span class="clickable icon-chevron-right" id="tweetsRight"></span>
			            </h2>
    			    </div>
    			</div>
    		</div> <!-- /title -->

    		<!--  ==========  -->
			<!--  = News content =  -->
			<!--  ==========  -->
    		<div class="row">
    		    <div class="span12">
    		        <div class="carouFredSel" data-nav="tweets" data-autoplay="false">


		                <!--  ==========  -->
						<!--  = Slide =  -->
						<!--  ==========  -->
                        {% for pages in slid_pages %}
                        <div class="slide">
                        	<div class="row">
                                {% for page in pages %}
                        		<div class="span6">
                        		    <div class="news-item">
                        		        <div class="published">{{ page.create|date:"d F Y" }}</div>
                        		        <h6><a href="{{ page.get_absolute_url }}">{{ page.name }}</a></h6>
                        		        <p><img src="{{ MEDIA_URL }}{{ page.images }}" />{{ page.min_text|linebreaksbr }}</p>
                        		    </div>
                        		</div>
                                {% endfor %}
                        	</div>
                        </div>
                        {% endfor %}

                        <!-- /slide -->

                    </div>
    		    </div>
    		</div> <!-- /news content -->
    	</div>

    </div> <!-- /latest news -->

    <!--  ==========  -->
    <!--  = Brands Carousel =  -->
    <!--  ==========  -->
	<div class="container">

	</div> <!-- /brands carousel -->

{% endblock %}









{% block upper_footer %}
    <!--  ==========  -->
        <!--  = Upper footer =  -->
        <!--  ==========  -->
        <div class="foot-light">
            <div class="container">
                <div class="row">
                    <div class="span4">
                        <h2 class="pacifico">{{ site.name }} &nbsp; <img src="{% static 'images/webmarket.png' %}" alt="{{ site.name }}" class="align-baseline" /></h2>
                        {% if request.META.PATH_INFO == '/' %}{% autoescape off %}{{ site.about }}{% endautoescape %}{% endif %}
                    </div>

                    <div class="span4">
                        <div class="main-titles lined">
                            <h3 class="title"><span class="light">Будь в курсе всех </span> скидок!</h3>
                        </div>
                        <p>Подпишись на рассылку акций и скидок.</p>
                        <!-- Begin MailChimp Signup Form -->
                        {% include 'email_code.html' %}
                        <!--End mc_embed_signup-->
                    </div>
                </div>
            </div>
        </div> <!-- /upper footer -->
{% endblock %}